# Generated by Django 2.1.4 on 2018-12-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cytometry', '0003_calcu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=''),
        ),
    ]
