# Generated by Django 2.1.4 on 2018-12-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cytometry', '0004_auto_20181207_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calcu',
        ),
    ]
